import {restoreLicense,validateLicense,logoutLicense} from './src/license.js';
import {visibleGames} from './src/catalog.js';
const gate=document.querySelector('#gate'),app=document.querySelector('#app'),form=document.querySelector('#licenseForm'),input=document.querySelector('#licenseKey'),button=document.querySelector('#verify'),statusEl=document.querySelector('#gateStatus');
function status(text,kind=''){statusEl.textContent=text;statusEl.dataset.kind=kind}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mountHall(session){const games=visibleGames(session.plan);gate.remove();app.hidden=false;app.innerHTML=`<header><a class="logo">NOT<span>.</span><small>HALL</small></a><nav><button class="active" data-filter="all">Todos</button><button data-filter="live">Para Live</button><button data-filter="casual">Casual</button><button data-filter="new">Novidades</button></nav><div class="right"><span class="plan">${esc(session.plan||'NOT')}</span><button class="logout" id="logout" type="button">Sair</button></div></header><main><section class="hero"><div class="hero-glow"></div><div class="hero-content"><div class="eyebrow">SUA BIBLIOTECA NOT</div><h1>Escolha. Jogue.<br>Entre ao vivo.</h1><p>Todos os jogos disponíveis na sua assinatura, organizados em um único Hall.</p></div></section><div class="toolbar"><div class="sectionTitle"><h2>Biblioteca</h2><span id="count"></span></div><label class="search">⌕ <input id="search" placeholder="Buscar na biblioteca..." autocomplete="off"></label></div><section><div class="grid" id="games"></div><div class="empty" id="empty">Nenhum jogo disponível para esta assinatura.</div></section></main>`;let filter='all';const grid=app.querySelector('#games'),search=app.querySelector('#search'),count=app.querySelector('#count'),empty=app.querySelector('#empty');function render(){const q=search.value.toLowerCase().trim(),list=games.filter(g=>(filter==='all'||g.cat===filter)&&String(g.name).toLowerCase().includes(q));grid.replaceChildren(...list.map(game=>{const el=document.createElement('article');el.className='game';el.tabIndex=0;el.innerHTML=`<div class="cover"><span class="tag">${esc(game.tag||'JOGO')}</span><div class="mark">NOT</div><span class="play">▶</span></div><h3>${esc(game.name)}</h3><p>${esc(game.desc||'Experiência NOT')}</p>`;el.onclick=()=>game.url&&location.assign(game.url);el.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&game.url){e.preventDefault();location.assign(game.url)}};return el}));count.textContent=`${list.length} disponíveis`;empty.style.display=list.length?'none':'block'}app.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{app.querySelector('nav .active')?.classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});search.oninput=render;app.querySelector('#logout').onclick=logoutLicense;render()}
async function submit(key){button.disabled=true;input.disabled=true;status('Validando sua assinatura…');try{const session=await validateLicense(key);status('Acesso liberado.','ok');mountHall(session)}catch(e){status(e.message||'Não foi possível confirmar a assinatura.','error');input.disabled=false;button.disabled=false;input.focus()}}
form.addEventListener('submit',e=>{e.preventDefault();submit(input.value)});
(async()=>{status('Verificando assinatura salva…');const session=await restoreLicense();if(session){mountHall(session);return}status('Digite sua chave NOT para continuar.');input.focus()})();
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});document.addEventListener('gestureend',e=>e.preventDefault(),{passive:false});let lastTouchEnd=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=now},{passive:false});document.addEventListener('touchmove',e=>{if(e.touches.length>1)e.preventDefault()},{passive:false});