const VALIDATE_URL='https://pa.wallissonghost.workers.dev/api/licenses/validate';
const STORAGE_KEY='not_license_key',DEVICE_KEY='not_device_id',REVALIDATE_MS=60_000,NETWORK_GRACE_MS=180_000;
let token=null,tokenExpiresAt=0,lastConfirmedAt=0,revalidateTimer=null,graceTimer=null;
function makeDeviceId(){const b=new Uint8Array(24);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
export function getDeviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id||!/^[A-Za-z0-9_-]{16,128}$/.test(id)){id=makeDeviceId();localStorage.setItem(DEVICE_KEY,id)}return id}
const deviceId=getDeviceId();
function reasonMessage(r){return({DEVICE_LIMIT_REACHED:'Limite de dispositivos atingido para esta assinatura.',DEVICE_REVOKED:'Este dispositivo foi removido da assinatura.',INVALID_DEVICE:'Este dispositivo não pôde ser identificado.',EXPIRED:'Assinatura expirada.',SUSPENDED:'Assinatura suspensa.',REVOKED:'Assinatura revogada.',TOO_MANY_ATTEMPTS:'Muitas tentativas. Aguarde e tente novamente.',INVALID_KEY:'Chave inválida.',SESSION_REQUIRED:'Sessão de licença inválida.',VALIDATION_UNAVAILABLE:'Não foi possível confirmar a assinatura agora.'}[r]||'Assinatura não autorizada.')}
async function request(key,activationMode){const res=await fetch(VALIDATE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,deviceId,activationMode}),cache:'no-store'});const data=await res.json().catch(()=>({}));return{res,data}}
function clearTimers(){if(revalidateTimer)clearInterval(revalidateTimer);if(graceTimer)clearTimeout(graceTimer);revalidateTimer=graceTimer=null}
function authorized(data,key){if(!data.sessionToken||!data.sessionExpiresAt)throw Object.assign(new Error('SESSION_REQUIRED'),{reason:'SESSION_REQUIRED'});token=data.sessionToken;tokenExpiresAt=Date.parse(data.sessionExpiresAt)||0;lastConfirmedAt=Date.now();localStorage.setItem(STORAGE_KEY,key);window.NOT_LICENSE=Object.freeze({authorized:true,status:'AUTHORIZED',plan:data.plan,expiresAt:data.expiresAt,deviceLimit:data.deviceLimit,activeDevices:data.activeDevices,lastConfirmedAt,sessionExpiresAt:data.sessionExpiresAt});window.dispatchEvent(new CustomEvent('not-license-authorized',{detail:window.NOT_LICENSE}));if(!revalidateTimer)revalidateTimer=setInterval(()=>revalidate(key),REVALIDATE_MS);return window.NOT_LICENSE}
export function lock(reason='INVALID_KEY',removeKey=false){clearTimers();token=null;tokenExpiresAt=0;if(removeKey)localStorage.removeItem(STORAGE_KEY);window.NOT_LICENSE=Object.freeze({authorized:false,status:'LOCKED',reason});window.dispatchEvent(new CustomEvent('not-license-locked',{detail:window.NOT_LICENSE}));return reasonMessage(reason)}
async function revalidate(key,final=false){try{const{res,data}=await request(key,'revalidate');if(!res.ok||!data.authorized){lock(data.reason||data.status||'INVALID_KEY',true);return false}authorized(data,key);return true}catch{if(final){lock('VALIDATION_UNAVAILABLE');return false}if(!token){lock('VALIDATION_UNAVAILABLE');return false}window.NOT_LICENSE=Object.freeze({...window.NOT_LICENSE,authorized:true,status:'GRACE_PERIOD',graceUntil:Date.now()+NETWORK_GRACE_MS});if(graceTimer)clearTimeout(graceTimer);graceTimer=setTimeout(()=>revalidate(key,true),NETWORK_GRACE_MS);return true}}
export async function validateLicense(rawKey,mode='activate'){const key=String(rawKey||'').trim().toUpperCase();if(!key)throw Object.assign(new Error('INVALID_KEY'),{reason:'INVALID_KEY'});try{const{res,data}=await request(key,mode);if(!res.ok||!data.authorized){const r=data.reason||data.status||'INVALID_KEY';lock(r,true);throw Object.assign(new Error(reasonMessage(r)),{reason:r})}return authorized(data,key)}catch(e){if(e?.reason)throw e;lock('VALIDATION_UNAVAILABLE');throw Object.assign(new Error(reasonMessage('VALIDATION_UNAVAILABLE')),{reason:'VALIDATION_UNAVAILABLE'})}}
export async function restoreLicense(){const key=localStorage.getItem(STORAGE_KEY);if(!key)return null;try{return await validateLicense(key,'revalidate')}catch{return null}}
export function savedKey(){return localStorage.getItem(STORAGE_KEY)||''}
export function logoutLicense(){lock('SIGNED_OUT',true);location.reload()}
Object.defineProperty(window,'NOT_LICENSE_SESSION',{configurable:false,enumerable:false,value:Object.freeze({getToken:()=>token&&Date.now()<tokenExpiresAt?token:null,getDeviceId:()=>deviceId,getSessionExpiresAt:()=>tokenExpiresAt,getLastConfirmedAt:()=>lastConfirmedAt})});
window.NOT_LICENSE=Object.freeze({authorized:false,status:'LOCKED'});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&token&&Date.now()-lastConfirmedAt>=REVALIDATE_MS){const key=localStorage.getItem(STORAGE_KEY);if(key)revalidate(key)}});
window.addEventListener('online',()=>{if(window.NOT_LICENSE?.status==='GRACE_PERIOD'){const key=localStorage.getItem(STORAGE_KEY);if(key)revalidate(key)}});
